apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  containers:
  - name: wordpress
    image: wordpress
    ports:
    - containerPort: 8080
    env:
      - name : WORDPRESS_DB_HOST
        value : sql
      - name : WORDPRESS_DB_USER
        value : wordpress
      - name : WORDPRESS_DB_PASSWORD
        value : wordpress
      - name : WORDPRESS_DB_NAME
        value : wordpress

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-pv-claim
  labels:
    app: sql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---      

apiVersion: v1
kind: Pod
metadata:
  name: sql
  labels:
    app: sql
spec:
  containers:
  - name: sql
    image: mysql:5.7
    ports:
    - containerPort: 3306
    env:
      - name : MYSQL_ROOT_PASSWORD
        value : somewordpress
      - name : MYSQL_DATABASE
        value : wordpress
      - name : MYSQL_USER
        value : wordpress
      - name : MYSQL_PASSWORD
        value : wordpress
    volumeMounts:
    - name: sqlvol
      mountPath: /var/lib/mysql
  volumes:
  - name: sqlvol
    persistentVolumeClaim:
      claimName: sql-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: sql
  labels:
    app: sql
spec:
  ports:
    - port: 3306
  selector:
    app: sql
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
  type: NodePort


